config/routes.rb
Rails.application.routes.draw do
  resources :actives
  resources :active_types
  resources :suppliers
  resources :kinds
  resources :brands
  resources :responsibles
  resources :invoices
  resources :groups
  resources :destinations
  resources :destinos
  resources :centers
  resources :zones

  namespace :api do
    namespace :v1 do
      resources :home, only: :index
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/active.rb
class Active < ApplicationRecord
end

app/models/active_type.rb
class ActiveType < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/center.rb
class Center < ApplicationRecord
end

app/models/destination.rb
class Destination < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
end

app/models/kind.rb
class Kind < ApplicationRecord
end

app/models/responsible.rb
class Responsible < ApplicationRecord
end

app/models/supplier.rb
class Supplier < ApplicationRecord
end

app/models/zone.rb
class Zone < ApplicationRecord
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]

  # GET /groups or /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1 or /groups/1.json
  def show
  end

  # GET groups/new
  def new
    @group = Group.new
  end

  # GET groups/1/edit
  def edit
    @group=Group.find(params[:id])
  end

  # POST /groups or groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_path, notice: 'Tu grupo se ha creado correctamente',  status: :see_other }
        format.json { render :show, status: :created, location: @group}
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to groups_path, notice: 'Tu producto se ha actualizado correctamente', status: :see_other }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    group = Group.find(params[:id])
    group.destroy
    redirect_to groups_path, notice: 'Tu producto se ha eliminado correctamente', status: :see_other
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:id, :name)
    end
end

app/helpers/active_types_helper.rb
module ActiveTypesHelper
end

app/helpers/actives_helper.rb
module ActivesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/centers_helper.rb
module CentersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this center from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <!--Se agrega campo para asignarle manualmente el ID a cada registro-->
 <div class="container mt-3">
  <div class="mb-3 mt-3">
    <%= form.label "Id del grupo", :class=>"form-label", style: "display: block" %>
    <%= form.text_field :id, :class=>"form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label "Nombre del grupo", :class=>"form-label", style: "display: block" %>
    <%= form.text_field :name, :class=>"form-control" %>
  </div>

  <div>
    <i class= "separar d-flex bi">
      <span class="">
        <%= button_tag(:type => 'submit', :title=>'Actualiza los datos', :class => 'bi bi-arrow-counterclockwise btn') do %>
          <i class="icon-up-arrow icon-white"></i>
        <% end %>
          
      </span>
        <%= link_to "", groups_path, :class=>"bi bi-skip-backward-btn-fill btn", :title=>'Retornar a grupos' %>
    </i>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>">
  <p>
    <strong>Name:</strong>
    <%= group.name %>
  </p>

</div>

app/views/groups/edit.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success" role="alert" id="notice" class="notice">
        <%= flash[:notice] %>                                    
    </div>
<% end %>

<div class="container">
  <div class="row">
      <div class="col-md-8">
        <div class="tzona">
            <h1>EDICIÓN DE GRUPOS</h1>
        </div>
      </div>
  </div>
</div>

<div class ="container">
  <div class="card card-dark text-white" style="width:100%">
    <div class="card-body">
      <h2 class="card-title"></h2>
      <div class="row">
        <div class="logo col-auto"><%= image_tag("record.png", :width => "200px") %></div>
          <div class="col">
            <h4 class="  card-title">DATOS DEL GRUPO</h4>
                <div class="centrarcard"><%= render "form", group: @group %></div><br>
            </div>
          </div>
        </div>
      </div>  
    </div>
  </div>
</div>
<br>
<div>

</div>

app/views/groups/index.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success" role="alert" id="notice" class="notice">
        <%= flash[:notice] %>                                    
    </div>
<% end %>

<!--Se agrega personalizacion con boostrap para visualizacion de las vistas de zonas -->
<div class="container">
  <!-- Stack the columns on mobile by making one full-width and the other half-width -->



  <nav class="navbar navsep navbar-expand-sm navbar-rednav bg-rednav rounded">
    <div class="container-fluid">
      <div class="navbar-collapse" id="mynavbar">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
          <i>
            <%= link_to " Nuevo Grupo", new_group_path, :class=>"nav-item nav-link bi bi-plus-square-dotted" %>
          </i>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="text" placeholder="group">
          <button class="btn btn-secondary" type="button">Buscar</button>
        </form>
      </div>
    </div>
  </nav>

  
  <div class="row">
      <div class="col-md-8">
        <div class="tzona">
            <h1>GRUPOS</h1>
        </div>
            <table class="table table-dark table-hover">
                  <tr class="text-dark">
                    <th>CÓDIGO</th>
                    <th>NOMBRE</th>
                    <th>ACCIONES</th>
                  </tr>
                      <div id="groups">
                        <% @groups.each do |group| %>
                          <tr>
                            <td>
                              <%= group.id%>
                            </td>
                            <td>
                              <%= group.name %>
                            </td>
                            <td>
                              <i class="separar">
                              <%= button_to "", group, method: :delete, :class=>"bi bi-trash btn", :data=>{turbo_confirm:'Estás seguro?'}%>
                              <%= link_to "", edit_group_path(group), :title=>"Editar", :class=>" bi bi-pencil-fill btn" %>
                              </i>
                            </td> 
                          </tr>
                        <% end %>
                      </div>
            </table> 
      </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class ="container">
  <div class="row">
      <div class="col-md-8">
        <div class="tzona">
            <h1>NUEVO GRUPO</h1>
        </div>
      </div>
  </div>
</div>          
<div class ="container">
  <div class="card card-dark text-white" style="width:100%">
    <div class="card-body">
      <h2 class="card-title"></h2>
      <div class="row">
        <div class="logo col-auto"><%= image_tag("record.png", :class => "", :width => "200px") %></div>
          <div class="col">
            <h4 class="card-title">DATOS DEL GRUPO</h4>
                <div class="centrarcard"><%= render "form", group: @group %></div>
            </div>
          </div>
        </div>
      </div>  
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group %>

<div>
  <%= link_to "Edit this group", edit_group_path(@group) %> |
  <%= link_to "Back to groups", groups_path %>

  <%= button_to "Destroy this group", @group, method: :delete %>
</div>