config/routes.rb
Rails.application.routes.draw do
  resources :actives
  resources :active_types
  resources :suppliers
  resources :kinds
  resources :brands
  resources :responsibles
  resources :invoices
  resources :groups
  resources :destinations
  resources :destinos
  resources :centers
  resources :zones

  namespace :api do
    namespace :v1 do
      resources :home, only: :index
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/active.rb
class Active < ApplicationRecord
end

app/models/active_type.rb
class ActiveType < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/center.rb
class Center < ApplicationRecord
end

app/models/destination.rb
class Destination < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
end

app/models/kind.rb
class Kind < ApplicationRecord
end

app/models/responsible.rb
class Responsible < ApplicationRecord
end

app/models/supplier.rb
class Supplier < ApplicationRecord
end

app/models/zone.rb
class Zone < ApplicationRecord
end

app/controllers/centers_controller.rb
class CentersController < ApplicationController
  before_action :set_center, only: %i[ show edit update destroy ]

  # GET /zones or /zones.json
  def index
    @centers = Center.all
  end

  # GET /zones/1 or /zones/1.json
  def show
  end

  # GET /zones/new
  def new
    @center = Center.new
    
  end

  # GET /zones/1/edit
  def edit
    @center=Center.find(params[:id])
  end

  # POST /zones or /zones.json
  def create
    @center = Center.new(center_params)

    respond_to do |format|
      if @center.save
        format.html { redirect_to centers_path, notice: 'Tu producto se ha creado correctamente', status: :see_other }
        format.json { render :show, status: :created, location: @center }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @center.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zones/1 or /zones/1.json
  def update
    respond_to do |format|
      if @center.update(center_params)
        format.html { redirect_to centers_path, notice: 'Tu producto se ha actualizado correctamente', status: :see_other }
        format.json { render :show, status: :ok, location: @center }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @center.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zones/1 or /zones/1.json
  def destroy
    center = Center.find(params[:id])
    center.destroy
    redirect_to centers_path, notice: 'Tu producto se ha eliminado correctamente', status: :see_other
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_center
      @center = Center.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def center_params
      params.require(:center).permit(:id, :name)
    end
end

app/helpers/active_types_helper.rb
module ActiveTypesHelper
end

app/helpers/actives_helper.rb
module ActivesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/centers_helper.rb
module CentersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/centers/_center.html.erb
<div id="<%= dom_id center %>">
  <p>
    <strong>Name:</strong>
    <%= center.name %>
  </p>

</div>

app/views/centers/_form.html.erb
<%= form_with(model: center) do |form| %>
  <% if center.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(center.errors.count, "error") %> prohibited this center from being saved:</h2>

      <ul>
        <% center.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <!--Se agrega campo para asignarle manualmente el ID a cada registro-->
 <div class="container mt-3">
  <div class="mb-3 mt-3">
    <%= form.label "Identificador del centro de costo", :class=>"form-label", style: "display: block" %>
    <%= form.text_field :id, :class=>"form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label "Nombre del centro de costo", :class=>"form-label", style: "display: block" %>
    <%= form.text_field :name, :class=>"form-control" %>
  </div>

  <div>
    <i class= "separar d-flex bi">
      <span class="">
        <%= button_tag(:type => 'submit', :title=>'Actualiza los datos', :class => 'bi bi-arrow-counterclockwise btn') do %>
          <i class="icon-up-arrow icon-white"></i>
        <% end %>
          
      </span>
        <%= link_to "", centers_path, :class=>"bi bi-skip-backward-btn-fill btn", :title=>'Retornar a las zonas' %>
    </i>
  </div>
<% end %>

app/views/centers/edit.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success" role="alert" id="notice" class="notice">
        <%= flash[:notice] %>                                    
    </div>
<% end %>

<div class="container">
  <div class="row">
      <div class="col-md-8">
        <div class="tzona">
            <h1>EDICIÓN DE CENTROS DE COSTO</h1>
        </div>
      </div>
  </div>
</div>

<div class ="container">
  <div class="card card-dark text-white" style="width:100%">
    <div class="card-body">
      <h2 class="card-title"></h2>
      <div class="row">
        <div class="logo col-auto"><%= image_tag("record.png", :width => "200px") %></div>
          <div class="col">
            <h4 class="  card-title">DATOS DEL CENTRO DE COSTO</h4>
                <div class="centrarcard"><%= render "form", center: @center %></div><br>
            </div>
          </div>
        </div>
      </div>  
    </div>
  </div>
</div>
<br>
<div>

</div>

app/views/centers/index.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success" role="alert" id="notice" class="notice">
        <%= flash[:notice] %>                                    
    </div>
<% end %>

<!--Se agrega personalizacion con boostrap para visualizacion de las vistas de zonas -->
<div class="container">
  <!-- Stack the columns on mobile by making one full-width and the other half-width -->



  <nav class="navbar navsep navbar-expand-sm navbar-rednav bg-rednav rounded">
    <div class="container-fluid">
      <div class="navbar-collapse" id="mynavbar">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
          <i>
            <%= link_to " Nuevo centro de costo", new_center_path, :class=>"nav-item nav-link bi bi-plus-square-dotted" %>
          </i>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="text" placeholder="center">
          <button class="btn btn-secondary" type="button">Buscar</button>
        </form>
      </div>
    </div>
  </nav>

  
  <div class="row">
      <div class="col-md-8">
        <div class="tzona">
            <h1>CENTROS DE COSTO</h1>
        </div>
            <table class="table table-dark table-hover">
                  <tr class="text-dark">
                    <th>CÓDIGO</th>
                    <th>NOMBRE</th>
                    <th>ACCIONES</th>
                  </tr>
                      <div id="centers">
                        <% @centers.each do |center| %>
                          <tr>
                            <td>
                              <%= center.id%>
                            </td>
                            <td>
                              <%= center.name %>
                            </td>
                            <td>
                              <i class="separar">
                              <%= button_to "", center, method: :delete, :class=>"bi bi-trash btn", :data=>{turbo_confirm:'Estás seguro?'}%>
                              <%= link_to "", edit_center_path(center), :title=>"Editar", :class=>" bi bi-pencil-fill btn" %>
                              </i>
                            </td> 
                          </tr>
                        <% end %>
                      </div>
            </table> 
      </div>
  </div>
</div>

app/views/centers/new.html.erb
<div class ="container">
  <div class="row">
      <div class="col-md-8">
        <div class="tzona">
            <h1>NUEVO CENTRO DE COSTO</h1>
        </div>
      </div>
  </div>
</div>          
<div class ="container">
  <div class="card card-dark text-white" style="width:100%">
    <div class="card-body">
      <h2 class="card-title"></h2>
      <div class="row">
        <div class="logo col-auto"><%= image_tag("record.png", :class => "", :width => "200px") %></div>
          <div class="col">
            <h4 class="card-title">DATOS DEL CENTRO DE COSTO</h4>
                <div class="centrarcard"><%= render "form", center: @center %></div>
            </div>
          </div>
        </div>
      </div>  
    </div>
  </div>
</div>

app/views/centers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @center %>

<div>
  <%= link_to "Edit this center", edit_center_path(@center) %> |
  <%= link_to "Back to centers", centers_path %>

  <%= button_to "Destroy this center", @center, method: :delete %>
</div>