config/routes.rb
Rails.application.routes.draw do
  resources :actives
  resources :active_types
  resources :suppliers
  resources :kinds
  resources :brands
  resources :responsibles
  resources :invoices
  resources :groups
  resources :destinations
  resources :destinos
  resources :centers
  resources :zones

  namespace :api do
    namespace :v1 do
      resources :home, only: :index
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/active.rb
class Active < ApplicationRecord
end

app/models/active_type.rb
class ActiveType < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/center.rb
class Center < ApplicationRecord
end

app/models/destination.rb
class Destination < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
end

app/models/kind.rb
class Kind < ApplicationRecord
end

app/models/responsible.rb
class Responsible < ApplicationRecord
end

app/models/supplier.rb
class Supplier < ApplicationRecord
end

app/models/zone.rb
class Zone < ApplicationRecord
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: %i[ show edit update destroy ]

  # GET /brands or /brands.json
  def index
    @brands = Brand.all
  end

  # GET /brands/1 or /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
    @brand=Brand.find(params[:id])
  end

  # POST /brands or /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to brands_path, notice: "Brand was successfully created." }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1 or /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to brands_path, notice: "Brand was successfully updated." }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1 or /brands/1.json
  def destroy
      brand = Brand.find(params[:id])
      brand.destroy
      redirect_to brands_path, notice: "Brand was successfully destroyed."
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def brand_params
      params.require(:brand).permit(:id, :name)
    end
end

app/helpers/active_types_helper.rb
module ActiveTypesHelper
end

app/helpers/actives_helper.rb
module ActivesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/centers_helper.rb
module CentersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/brands/_brand.html.erb
<div id="<%= dom_id brand %>">
  <p>
    <strong>Name:</strong>
    <%= brand.name %>
  </p>

</div>

app/views/brands/_form.html.erb
<%= form_with(model: brand) do |form| %>
  <% if brand.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
        <% brand.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!--Se agrega campo para asignarle manualmente el ID a cada registro-->
  <div class="container mt-3">
   <div class="mb-3 mt-3">
     <%= form.label "Identificador de la marca", :class=>"form-label", style: "display: block" %>
     <%= form.text_field :id, :class=>"form-control" %>
   </div>
   <div class="mb-3">
     <%= form.label "Nombre de la marca", :class=>"form-label", style: "display: block" %>
     <%= form.text_field :name, :class=>"form-control" %>
   </div>
 
   <div>
     <i class= "separar d-flex bi">
       <span class="">
         <%= button_tag(:type => 'submit', :title=>'Actualiza los datos', :class => 'bi bi-arrow-counterclockwise btn') do %>
           <i class="icon-up-arrow icon-white"></i>
         <% end %>
           
       </span>
         <%= link_to "", brands_path, :class=>"bi bi-skip-backward-btn-fill btn", :title=>'Retornar a las zonas' %>
     </i>
   </div>
 <% end %>
 

app/views/brands/edit.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success" role="alert" id="notice" class="notice">
        <%= flash[:notice] %>                                    
    </div>
<% end %>

<div class="container">
  <div class="row">
      <div class="col-md-8">
        <div class="tzona">
            <h1>EDICIÓN DE LA MARCA</h1>
        </div>
      </div>
  </div>
</div>

<div class ="container">
  <div class="card card-dark text-white" style="width:100%">
    <div class="card-body">
      <h2 class="card-title"></h2>
      <div class="row">
        <div class="logo col-auto"><%= image_tag("record.png", :width => "200px") %></div>
          <div class="col">
            <h4 class="  card-title">DATOS DE LA MARCA</h4>
                <div class="centrarcard"><%= render "form", brand: @brand %></div><br>
            </div>
          </div>
        </div>
      </div>  
    </div>
  </div>
</div>
<br>
<div>

</div>

app/views/brands/index.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success" role="alert" id="notice" class="notice">
        <%= flash[:notice] %>                                    
    </div>
<% end %>

<!--Se agrega personalizacion con boostrap para visualizacion de las vistas de zonas -->
<div class="container">
  <!-- Stack the columns on mobile by making one full-width and the other half-width -->



  <nav class="navbar navsep navbar-expand-sm navbar-rednav bg-rednav rounded">
    <div class="container-fluid">
      <div class="navbar-collapse" id="mynavbar">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
          <i>
            <%= link_to " Añadir nueva marca", new_brand_path, :class=>"nav-item nav-link bi bi-plus-square-dotted" %>
          </i>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="text" placeholder="brand">
          <button class="btn btn-secondary" type="button">Buscar</button>
        </form>
      </div>
    </div>
  </nav>

  
  <div class="row">
      <div class="col-md-8">
        <div class="tzona">
            <h1>MARCAS</h1>
        </div>
            <table class="table table-dark table-hover">
                  <tr class="text-dark">
                    <th>CÓDIGO DE MARCA</th>
                    <th>NOMBRE DE MARCA</th>
                    <th>ACCIONES</th>
                  </tr>
                      <div id="brands">
                        <% @brands.each do |brand| %>
                          <tr>
                            <td>
                              <%= brand.id%>
                            </td>
                            <td>
                              <%= brand.name %>
                            </td>
                            <td>
                              <i class="separar">
                              <%= button_to "", brand, method: :delete, :class=>"bi bi-trash btn", :data=>{turbo_confirm:'Estás seguro?'}%>
                              <%= link_to "", edit_brand_path(brand), :title=>"Editar", :class=>" bi bi-pencil-fill btn" %>
                              </i>
                            </td> 
                          </tr>
                        <% end %>
                      </div>
            </table> 
      </div>
  </div>
</div>

app/views/brands/new.html.erb
<div class ="container">
  <div class="row">
      <div class="col-md-8">
        <div class="tzona">
            <h1>NUEVA MARCA</h1>
        </div>
      </div>
  </div>
</div>          
<div class ="container">
  <div class="card card-dark text-white" style="width:100%">
    <div class="card-body">
      <h2 class="card-title"></h2>
      <div class="row">
        <div class="logo col-auto"><%= image_tag("record.png", :class => "", :width => "200px") %></div>
          <div class="col">
            <h4 class="card-title">DATOS DE LA MARCA</h4>
                <div class="centrarcard"><%= render "form", brand: @brand %></div>
            </div>
          </div>
        </div>
      </div>  
    </div>
  </div>
</div>

app/views/brands/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @brand %>

<div>
  <%= link_to "Edit this brand", edit_brand_path(@brand) %> |
  <%= link_to "Back to brands", brands_path %>

  <%= button_to "Destroy this brand", @brand, method: :delete %>
</div>